### ISSUE TITLE
Cannot incrementally apply new template + common tenant variable to existing library variable set

### ISSUE THREAD

**Issue by mbenson** [OctopusDeployLabs/terraform-provider-octopusdeploy#216] opened 2021-07-16 17:51 UTC
**Describe the bug**
Reference to library variable set template IDs requires that the whole LVS not exist, or that the referenced template _preexist_.

**Steps to reproduce**

Using the following terraform configuration, which is based on the resource unit test:

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
      version = "~> 0.7.43"
    }
  }
}

provider "octopusdeploy" {
  address  = var.octo_address
  api_key  = var.octo_api_key
  space_id = "Spaces-1"
}

variable "octo_address" {
  type = string
}

variable "octo_api_key" {
  type = string
}

resource "octopusdeploy_library_variable_set" "common_tenant_var" {
  name = "common_tenant_var"

  # template {
  #   default_value = "Default Value???"
  #   help_text     = "This is the help text"
  #   label         = "Test Label"
  #   name          = "Test Template"

  #   display_settings = {
  #     "Octopus.ControlType" = "SingleLineText"
  #   }
  # }
}

# resource "octopusdeploy_project" "common_tenant_var" {
#   included_library_variable_sets = [octopusdeploy_library_variable_set.common_tenant_var.id]
#   lifecycle_id                   = "Lifecycles-1"
#   name                           = "common_tenant_var"
#   project_group_id               = "ProjectGroups-1"
# }

# resource "octopusdeploy_tenant" "common_tenant_var" {
#   name = "common_tenant_var"

#   project_environment {
#     project_id   = octopusdeploy_project.common_tenant_var.id
#     environments = ["Environments-1"]
#   }
# }

# resource "octopusdeploy_tenant_common_variable" "common_tenant_var" {
#   library_variable_set_id = octopusdeploy_library_variable_set.common_tenant_var.id
#   tenant_id               = octopusdeploy_tenant.common_tenant_var.id
#   variable_id             = octopusdeploy_library_variable_set.common_tenant_var.template[0].id
#   value                   = octopusdeploy_tenant.common_tenant_var.name
# }
```

1. Satisfy the `octo_address` and `octo_api_key` variables, e.g. using `.auto.tfvars.json`
2. `terraform apply`
3. Uncomment commented sections
4. `terraform plan`... an error should be generated to the effect that `variable_id` has not been set (is `null`)

To confirm that this behavior only occurs in the case that the LVS exists (but the template within does not), simply `terraform destroy` the original (partially commented) configuration, then uncomment and `terraform plan` will show that the common variable's `variable_id` will be `(known after apply)`.

**Expected behavior**
I don't know if it is technically possible, but I would have hoped to be able to apply incremental changes with the same success as encountered with a "green field" configuration.

**Logs and other supporting information**
```
╷
│ Error: Missing required argument
│ 
│   with octopusdeploy_tenant_common_variable.common_tenant_var,
│   on main.tf line 60, in resource "octopusdeploy_tenant_common_variable" "common_tenant_var":
│   60:   variable_id             = octopusdeploy_library_variable_set.common_tenant_var.template[0].id
│ 
│ The argument "variable_id" is required, but no definition was found.
╵
```

**Environment and versions:**
- OS: `OSX`
- Octopus Server Version: `2021.1.7508`
- Terraform Version: `1.0.0`
- Octopus Terraform Provider Version: `0.7.43`

**Additional context**

**Comment by jbristowe** [comment] 2021-07-19 21:28
Looking into this. By the way, these HCL configurations are super-useful when diagnosing this kind of behaviour. Much appreciated! 👍

**Comment by mbenson** [comment] 2021-07-19 23:53
Maybe being thick, but my brain isn't parsing "HCL." 🙂

**Comment by jbristowe** [comment] 2021-07-19 23:59
https://github.com/hashicorp/hcl

**Comment by jbristowe** [comment] 2021-07-20 01:27
I cannot reproduce this behaviour. I've tried several variations of the setup. Essentially, Terraform is reporting that `variable_id` is `null`, which leads me to suspect that `octopusdeploy_library_variable_set. common_tenant_var` wasn't updated. You can get a better sense of what's happening under-the-covers by setting the environment variable, `TF_LOG` to `TRACE` (see [Debugging Terraform](https://www.terraform.io/docs/internals/debugging.html)).

**Comment by mbenson** [comment] 2021-07-23 23:31
Wow, can't believe you can't reproduce. The trace logging created quite a ream of output... any hint on what I could/should be looking for?

**Comment by johnsimons** [comment] 2023-02-22 04:55
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 04:55 UTC
