### ISSUE TITLE
Resource to create user API keys

### ISSUE THREAD

**Issue by mgust** [OctopusDeployLabs/terraform-provider-octopusdeploy#495] opened 2023-03-10 15:36 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to use Terraform to deploy and configure Octopus Tentacles. I would like to create a service user for each Tentacle (each representing a Nomad cluster), create an API key and store it Vault and then deploy the Tentacle.
At the moment the only manual step in this is the "create an API key" above.

**Describe the solution you'd like**
An "octopusdeploy_user_apikey" resource to create and manage API keys would help close the circle to automate the deployment.

**Describe alternatives you've considered**
Whilst we could in theory expose the tentacle to the Internet and deploy it using octopusdeploy_listening_tentacle_deployment_target I prefer the simplicity of only having outgoing calls rather than having to create an additional entrypoint to my cluster.

**Comment by 2good4hisowngood** [comment] 2023-09-26 21:07
Came here to seek this as well. 
It'd be great to automate the replacement of keys across an array of resources by having individual keys generated by terraform, cross reference resources into the descriptions/names of the keys where relevant, and be able to automate replacing them regularly.

As an intermediate step, I think there's an executable resource where I can pipe in some code, so I might try an API call to octopus mid deployment to collect the key.

**Comment by Desarc** [comment] 2024-05-23 07:16
+1

We use Terraform primarily to automate users, teams and user roles across our many spaces. A resource for API keys would allow us to easily generate new keys with specific permissions for new use cases, or revoke/regenerate existing ones. Terraform already integrates with our secret manager (Hashicorp Vault), and most of our API key consumers also have similar integrations. At the moment, this is the only manual step in the process, since we have to log in to the UI, find the user, create an API key, and then copy it to the appropriate place in our secret manager. The manual process also makes it hard to keep track of which API keys are currently active and in use.

**Comment by mjhilton** [comment] 2024-09-10 05:11
Closing as duplicate of #206

**Closed by mjhilton** 2024-09-10 05:11 UTC
Labels: closed/duplicate, kind/enhancement
