### ISSUE TITLE
Raw actions conflict with specialised resources like run_script_action on second apply

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeployLabs/terraform-provider-octopusdeploy#509] opened 2023-04-05 23:28 UTC
**Describe the bug**
When a deployment process uses plain `action` resources, they can not be reapplied as the provider sends invalid JSON to the server.

**Steps to reproduce**
1. Apply the sample configuration below. This initially succeeds.
2. Reapply the sample configuration. An error is produced about duplicate action names.

**Sample Configuration**
```
data "octopusdeploy_lifecycles" "example" {
  ids          = []
  partial_name = "Default Lifecycle"
  skip         = 0
  take         = 1
}

data "octopusdeploy_project_groups" "example" {
  ids          = []
  partial_name = "Default"
  skip         = 0
  take         = 1
}

terraform {

  required_providers {
    octopusdeploy = { source =  "octopus.com/com/octopusdeploy", version = "0.11.1" }
  }
}

variable "octopus_server" {
  type        = string
  nullable    = false
  sensitive   = false
  description = "The URL of the Octopus server e.g. https://myinstance.octopus.app."
}
variable "octopus_apikey" {
  type        = string
  nullable    = false
  sensitive   = true
  description = "The API key used to access the Octopus server. See https://octopus.com/docs/octopus-rest-api/how-to-create-an-api-key for details on creating an API key."
}
variable "octopus_space_id" {
  type        = string
  nullable    = false
  sensitive   = false
  description = "The ID of the Octopus space to populate."
}

data "octopusdeploy_channels" "channel_default" {
  ids          = null
  partial_name = "Default"
  skip         = 0
  take         = 1
}

resource "octopusdeploy_deployment_process" "deployment_process_project_noopterraform" {
  project_id = "${octopusdeploy_project.project_noopterraform.id}"

  step {
    condition           = "Success"
    name                = "Hello world (using PowerShell) - clone (1)"
    package_requirement = "LetOctopusDecide"
    start_trigger       = "StartAfterPrevious"

    action {
      action_type                        = "Octopus.Script"
      name                               = "Hello world (using PowerShell) - clone (1)"
      condition                          = "Success"
      run_on_server                      = true
      is_disabled                        = false
      can_be_used_for_project_versioning = false
      is_required                        = true
      worker_pool_id                     = ""
      properties                         = {
        "Octopus.Action.Script.ScriptSource" = "Inline"
        "Octopus.Action.Script.ScriptBody" = "Write-Host 'Hello world, using PowerShellwith an update'\n\n#TODO: Experiment with steps of your own :)\n\nWrite-Host '[Learn more about the types of steps available in Octopus](https://oc.to/OnboardingAddStepsLearnMore)'"
        "Octopus.Action.Script.Syntax" = "PowerShell"
      }
      environments                       = []
      excluded_environments              = []
      channels                           = []
      tenant_tags                        = []
      features                           = []
    }

    properties   = {}
    target_roles = []
  }
}

provider "octopusdeploy" {
  address  = "${var.octopus_server}"
  api_key  = "${var.octopus_apikey}"
  space_id = "${var.octopus_space_id}"
}


resource "octopusdeploy_project" "project_noopterraform" {
  name                                 = "Terraform Bug Project"
  auto_create_release                  = false
  default_guided_failure_mode          = "EnvironmentDefault"
  default_to_skip_if_already_installed = false
  description                          = ""
  discrete_channel_release             = false
  is_disabled                          = false
  is_version_controlled                = false
  lifecycle_id                         = "${data.octopusdeploy_lifecycles.example.lifecycles[0].id}"
  project_group_id                     = "${data.octopusdeploy_project_groups.example.project_groups[0].id}"
  included_library_variable_sets       = []
  tenanted_deployment_participation    = "Untenanted"

  connectivity_policy {
    allow_deployments_to_no_targets = true
    exclude_unhealthy_targets       = false
    skip_machine_behavior           = "None"
  }

  versioning_strategy {
    template = "#{Octopus.Version.LastMajor}.#{Octopus.Version.LastMinor}.#{Octopus.Version.NextPatch}"
  }
}
```

**Expected behavior**
The deployment process should be applied correctly.

**Logs and other supporting information**
```
Error: octopus deploy api returned an error on endpoint /api/Spaces-282/projects/Projects-4107/deploymentprocesses - [Action name 'Hello world (using PowerShell) - clone (1)' is already in use by another action in this deployment process. Action names must be unique. Please select one or more roles that 'Hello world (using PowerShell) - clone (1)' step will apply to.]
```

**Environment and versions:**
- OS: Linux
- Octopus Server Version: v2023.2 (Build 4954)
- Terraform Version: v1.4.4
- Octopus Terraform Provider Version: 0.11.1

**Comment by mcasperson** [comment] 2023-04-05 23:35
The issue here is due to the combination of optional and computed attributes, and the fact that an action has multiple different representations in the Terraform provider, but only one representation on the server.

What happens is this:
1. When the configuration is applied the first time, there is no state, and so the only representation of the action is what is found in the configuration file. This works as expected.
2. Once the configuration file is applied, the state of the actions is read from the returned JSON. The process of reading this state eventually runes through `flattenDeploymentSteps()`, which detects that the action is a script step, and persists it in the state as a `run_script_action` resource.
3. The next time the configuration is applied, Terraform has no way to know that the raw `action` resource is actually the same thing as the `run_script_action` in the state. Because `action` and `run_script_action` are both optional and computed, they are merged into the resource sent to the server. To quote from [this issue](https://github.com/hashicorp/terraform/issues/22605#issuecomment-528629997):
  > This is a known consequence of how some providers configured their resources, often relying on undefined behavior in older versions of terraform.
  > This block is defined as both optional and computed in the schema, so when a value already exists in the state, removing it from the config will leave the existing value as it may have been computed. There could be a couple workarounds for this, but they will require changes in the provider, and understanding of how this block is intended to be used internally.
4. Octopus rejects the update because two actions with the same name were defined.

There appears to be no nice workaround to "zero out" optional and computed blocks. To quote from [this issue](https://github.com/hashicorp/terraform-provider-google/issues/4326):

> Blocks have no zero value, so they can't be unset. Currently we're getting around that by using a gross hack that lets us continue to use block = [], but that's not going to stick around forever, so we need to find a new solution that is more inline with the type system.

**Comment by zentron** [comment] 2023-04-06 04:37
Duplicate of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/457

**Closed** 2023-04-06 05:55 UTC
