### ISSUE TITLE
Error creating octopusdeploy_kubernetes_cluster_deployment_target

### ISSUE THREAD

**Issue by antonioc74** [OctopusDeployLabs/terraform-provider-octopusdeploy#195] opened 2021-06-10 06:18 UTC
**Describe the bug**
Trying to create Octopus resource "octopusdeploy_kubernetes_cluster_deployment_target"

Get error:

```
Error: Octopus API error: Value cannot be null.
Parameter name: source []
```

**Steps to reproduce**
1. Go to 'Add resources to create required resources and use data source for Environments '
2. Click on 'run terraform apply'

**Expected behavior**

**Logs and other supporting information**
Add the output of running `tf plan` or `tf apply` along with any errors in the Octopus Server logs.
Terraform plan output 
 ```
 # module.kubernetes_octopus_blue.data.octopusdeploy_environments.current_env[0] will be read during apply
  # (config refers to values not yet known)
 <= data "octopusdeploy_environments" "current_env"  {
      ~ id   = "Environments 2021-06-09 16:01:21.8593816 +0000 UTC" -> "Environments 2021-06-09 16:01:43.9100801 +0000 UTC"
        name = "plat-dev-00-xxx"
        take = 1

        environments {
            allow_dynamic_infrastructure = false
            id                           = "Environments-541"
            name                         = "plat-dev-00-xxx"
            sort_order                   = 17
            use_guided_failure           = false
        }
    }

  # module.kubernetes_octopus_blue.octopusdeploy_kubernetes_cluster_deployment_target.target[0] will be created
  + resource "octopusdeploy_kubernetes_cluster_deployment_target" "target" {
      + cluster_certificate               = "certificates-plat-dev-00-blue-xxx-crt-spaces-1"
      + cluster_url                       = "https://35.xxx.xxx.xxx"
      + environments                      = [
          + "Environments-541",
        ]
      + has_latest_calamari               = (known after apply)
      + health_status                     = (known after apply)
      + id                                = (known after apply)
      + is_disabled                       = (known after apply)
      + is_in_process                     = (known after apply)
      + machine_policy_id                 = (known after apply)
      + name                              = "plat-dev-00-blue-xxx-deployment-target"
      + operating_system                  = (known after apply)
      + roles                             = [
          + "PlatformDev",
        ]
      + shell_name                        = (known after apply)
      + shell_version                     = (known after apply)
      + space_id                          = (known after apply)
      + status                            = (known after apply)
      + status_summary                    = (known after apply)
      + tenant_tags                       = (known after apply)
      + tenanted_deployment_participation = "Untenanted"
      + thumbprint                        = (known after apply)
      + uri                               = (known after apply)

      + authentication {
          + account_id = "token-plat-dev-00-blue-xxx-tkn-spaces-1"
        }
```
#########################################
Octopus log:

```
2021-06-10 07:11:10.5341  10084     61 ERROR  Unhandled error on request: https://octopusdeploy.companyname.local/api/Spaces-1/machines d0c2dcc640894f7d88139bfa3a78069f by <anonymous> : Value cannot be null.
Parameter name: source
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Rules.TenantsFiltersAndTenantedDeploymentParticipationAgreeRule.BeforeMap(IParticipateInTenantedDeployments model, IParticipateInTenantedDeployments resource, ISpecialRuleContext context) in C:\buildAgent\work\b3c6a5d449cb5fde\source\Octopus.Server\Web\Api\Rules\TenantsFiltersAndTenantedDeploymentParticipationAgreeRule.cs:line 16
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRegisteredRules[TRule](Action`2 ruleCallback, IOctopusRelationalTransaction transaction) in C:\buildAgent\work\b3c6a5d449cb5fde\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 60
   at Octopus.Server.Web.Infrastructure.Api.CustomCreateResponder`3.ExecuteRegistered() in C:\buildAgent\work\b3c6a5d449cb5fde\source\Octopus.Server\Web\Infrastructure\Api\CustomCreateResponder.cs:line 55
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in C:\buildAgent\work\b3c6a5d449cb5fde\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 40
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object o, CancellationToken x) in C:\buildAgent\work\b3c6a5d449cb5fde\source\Octopus.Server\Web\Infrastructure\OctopusNancyModule.cs:line 125
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()
2021-06-10 07:11:35.0147  10084     25  INFO  Executing reader took 305ms in transaction 'ListTasksResponder': SELECT State, 
       Count(*) AS Counter 
FROM   (SELECT CASE 
                 WHEN HasPendingInterruptions = 1 AND [State] IN ( 'Queued', 'Executing' ) 
				 THEN 'Interrupted' 
                 ELSE [State] 
               END AS State,
		       SpaceId
        FROM ServerTask) AS _ 
WHERE ([SpaceId] = @_SpaceId_0_931 OR [SpaceId] IS NULL)
GROUP BY State
```
##############################
Terraform Apply see error
**Screenshots**
![image](https://user-images.githubusercontent.com/48080338/121399362-40febb00-c94e-11eb-9863-87b40c591615.png)

**Environment and versions:**
- OS: [e.g. `Windows`]
- Octopus Server Version: [e.g. `2019.12.14`]
- Terraform Version: [e.g. `0.13.3`]
- Octopus Terraform Provider Version: [e.g. `0.7.36`]

**Additional context**

**Comment by jbristowe** [comment] 2021-06-21 05:06
Hey @antonioc74. 👋 Thanks for submitting this issue. I wish to confirm the following in your configuration (above):

* `cluster_certificate` refers to the certificate ID (not its name)
* `account_id` refers to the account ID (not its name)

Please note that this issue appears to be related to #162

**Comment by antonioc74** [comment] 2021-06-21 09:29
Hi John, 

Thanks for your response. 

For the `cluster_certificate` we are pointing to the certificate ID
For the `account_id `we are also pointing to the id. 

```
resource "octopusdeploy_kubernetes_cluster_deployment_target" "target" {
  count = var.should_prepare_k8s_destruction ? 0 : 1
	
  cluster_url         = var.kubernetes_url
  environments        = data.octopusdeploy_environments.current_env.environments[*].id
  name                = "${local.long_name}-deployment-target"
  roles               = var.target_roles
  cluster_certificate = octopusdeploy_certificate.k8s_cert[0].id
  authentication {
    account_id = octopusdeploy_token_account.kubernetes_token[0].id
  }
} 
```

I found that article around the time we first came across this issue to try and identify the problem, but that didn't help.

Your comment on the Octopus trace talks about tenants https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/162#issuecomment-824509219, but we don't have tenants defined in our Octopus environment.

For now we have removed the deployment target code block from our Terraform, it until we identify the issue.

**Comment by ebuna** [comment] 2021-07-29 22:20
I am running into a similar issue, but the error I am receiving is slightly different: 
`Error: octopus deploy api returned an error on endpoint /api/Spaces-1/machines - [Account or certificate must be defined]`

The error is a bit misleading to me because the documentation does not show either of those as being required, and even so, we have specified `certificate_authentication`. For reference, here is what I have configured:
```hcl
resource "octopusdeploy_kubernetes_cluster_deployment_target" "k8s_dr_deployment_target" {
  cluster_url                        = "redacted_cluster_url"
  environments                       = [ "Environments-161" ]
  name                               = "k8s-dr-cluster-name"
  roles                              = [ "kubernetes" ]
  tenanted_deployment_participation  = "TenantedOrUntenanted"
  tenant_tags                        = [ "Region/uk" ]
  cluster_certificate                = octopusdeploy_certificate.k8s_dr_ca_certificate.id

  certificate_authentication {
    client_certificate = octopusdeploy_certificate.k8s_dr_certificate.id
  }
}
```

The 2 referenced certificates applied successfully and it is correctly pulling the ID of each, so I don't believe that is where the issue lies. When I enabled trace logging, I found this:

```
2021/07/29 21:38:17 [WARN] Provider "registry.terraform.io/octopusdeploylabs/octopusdeploy" produced an invalid plan for octopusdeploy_kubernetes_cluster_deployment_target.k8s_dr_deployment_target, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .authentication: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .aws_account_authentication: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .azure_service_principal_authentication: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .container: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .endpoint: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
```

I'm not sure if I am missing a needed config or if I have one configured incorrectly, and unfortunately the documentation is not very clear. It plans successfully:

```
# octopusdeploy_kubernetes_cluster_deployment_target.k8s_dr_deployment_target will be created
  + resource "octopusdeploy_kubernetes_cluster_deployment_target" "k8s_dr_deployment_target" {
      + cluster_certificate               = "Certificates-101"
      + cluster_url                       = "redacted_cluster_url"
      + environments                      = [
          + "Environments-161",
        ]
      + has_latest_calamari               = (known after apply)
      + health_status                     = (known after apply)
      + id                                = (known after apply)
      + is_DISABLED                       = (known after apply)
      + is_in_process                     = (known after apply)
      + machine_policy_id                 = (known after apply)
      + name                              = "k8s-dr-cluster-name"
      + operating_system                  = (known after apply)
      + roles                             = [
          + "kubernetes",
        ]
      + shell_name                        = (known after apply)
      + shell_version                     = (known after apply)
      + space_id                          = (known after apply)
      + status                            = (known after apply)
      + status_summary                    = (known after apply)
      + tenant_tags                       = [
          + "Region/uk",
        ]
      + tenanted_deployment_participation = "TenantedOrUntenanted"
      + tenants                           = (known after apply)
      + thumbprint                        = (known after apply)
      + uri                               = (known after apply)

      + authentication {
          + account_id = (known after apply)
        }

      + aws_account_authentication {
          + account_id                   = (known after apply)
          + assume_role                  = (known after apply)
          + assume_role_external_id      = (known after apply)
          + assume_role_session_duration = (known after apply)
          + assumed_role_arn             = (known after apply)
          + assumed_role_session         = (known after apply)
          + cluster_name                 = (known after apply)
          + use_instance_role            = (known after apply)
        }

      + azure_service_principal_authentication {
          + account_id             = (known after apply)
          + cluster_name           = (known after apply)
          + cluster_resource_group = (known after apply)
        }

      + certificate_authentication {
          + client_certificate = "Certificates-102"
        }

      + container {
          + feed_id = (known after apply)
          + image   = (known after apply)
        }

      + endpoint {
          + aad_client_credential_secret    = (known after apply)
          + aad_credential_type             = (known after apply)
          + aad_user_credential_username    = (known after apply)
          + account_id                      = (known after apply)
          + applications_directory          = (known after apply)
          + certificate_signature_algorithm = (known after apply)
          + certificate_store_location      = (known after apply)
          + certificate_store_name          = (known after apply)
          + client_certificate_variable     = (known after apply)
          + cloud_service_name              = (known after apply)
          + cluster_certificate             = (known after apply)
          + cluster_url                     = (known after apply)
          + communication_style             = (known after apply)
          + connection_endpoint             = (known after apply)
          + default_worker_pool_id          = (known after apply)
          + dot_net_core_platform           = (known after apply)
          + fingerprint                     = (known after apply)
          + host                            = (known after apply)
          + id                              = (known after apply)
          + namespace                       = (known after apply)
          + port                            = (known after apply)
          + proxy_id                        = (known after apply)
          + resource_group_name             = (known after apply)
          + running_in_container            = (known after apply)
          + security_mode                   = (known after apply)
          + server_certificate_thumbprint   = (known after apply)
          + skip_tls_verification           = (known after apply)
          + slot                            = (known after apply)
          + storage_account_name            = (known after apply)
          + swap_if_possible                = (known after apply)
          + thumbprint                      = (known after apply)
          + uri                             = (known after apply)
          + use_current_instance_count      = (known after apply)
          + web_app_name                    = (known after apply)
          + web_app_slot_name               = (known after apply)
          + working_directory               = (known after apply)

          + authentication {
              + account_id                   = (known after apply)
              + admin_login                  = (known after apply)
              + assume_role                  = (known after apply)
              + assume_role_external_id      = (known after apply)
              + assume_role_session_duration = (known after apply)
              + assumed_role_arn             = (known after apply)
              + assumed_role_session         = (known after apply)
              + authentication_type          = (known after apply)
              + client_certificate           = (known after apply)
              + cluster_name                 = (known after apply)
              + cluster_resource_group       = (known after apply)
              + use_instance_role            = (known after apply)
            }

          + container {
              + feed_id = (known after apply)
              + image   = (known after apply)
            }

          + destination {
              + destination_type = (known after apply)
              + drop_folder_path = (known after apply)
            }

          + tentacle_version_details {
              + upgrade_locked    = (known after apply)
              + upgrade_required  = (known after apply)
              + upgrade_suggested = (known after apply)
              + version           = (known after apply)
            }
        }
    }
```

Hopefully this can help track down where the issue is. I can try to provide more info if this is helpful.

**Comment by johnsimons** [comment] 2023-02-22 04:42
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 04:42 UTC
