### ISSUE TITLE
Add possibility to use step templates as a template in deployment process

### ISSUE THREAD

**Issue by DamienDaco** [OctopusDeployLabs/terraform-provider-octopusdeploy#359] opened 2022-03-21 12:40 UTC
**Is your feature request related to a problem? Please describe.**
When creating a new octopusdeploy_deployment_process with Terraform, we would like to reference an existing step template from our library.
Our step templates contain parameters with default values, and a script body.

However, when applying Terraform, it fails with the following error : 

> Error: octopus deploy api returned an error on endpoint /api/Spaces-1/deploymentprocesses/deploymentprocess-Projects-625 - [**Please provide the script body to run.**]

That behavior defeats the purpose of using an existing library step template.
We do not want to provide parameters and a script body, we would like the provider to be able to retrieve it from the library, just like like the GUI does when adding a step template into a project.
The existing step templates shall remain the single source of truth if possible.

Code:

Project.tf
```hcl
resource "octopusdeploy_project" "prototype-project" {
  name                                 = "POC - Prototype Project"
  description                          = "POC - TERRAFORMED"
  auto_create_release                  = false
  default_guided_failure_mode          = "EnvironmentDefault"
  default_to_skip_if_already_installed = false
  discrete_channel_release             = null
  is_disabled                          = false
  is_discrete_channel_release          = false
  is_version_controlled                = false
  lifecycle_id                         = "Lifecycles-301"
  project_group_id                     = "ProjectGroups-261"
  tenanted_deployment_participation    = "Tenanted"
  space_id                             = "Spaces-1"
}
```

Deployment-Process.tf
```hcl
resource "octopusdeploy_deployment_process" "MyProject01" {
  project_id = octopusdeploy_project.prototype-project.id
  space_id   = "Spaces-1"
  step {
    condition           = "Success"
    name                = "Deploy My Project 01"
    package_requirement = "LetOctopusDecide"
    target_roles        = ["MyProject 01"]
    start_trigger       = "StartAfterPrevious"
    run_script_action {
      action_template {
        id = "ActionTemplates-304"
      }
      can_be_used_for_project_versioning = false
      channels              = []
      condition             = "Success"
      environments          = []
      excluded_environments = []
      features              = []
      is_disabled           = false
      is_required           = false
      name                  = "Config Ini Generator - 01"
      run_on_server         = false
      script_source = "Inline"
      script_syntax = "PowerShell"
      tenant_tags   = []
    }
  }
}
```

Best regards,
Damien

Edit: I realize this is very similar to #137

**Comment by zentron** [comment] 2024-04-22 21:46
duplicate of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/137

**Comment by mjhilton** [comment] 2024-09-10 00:28
Closing as a duplicate of #137 where we'll track this work.

**Closed by mjhilton** 2024-09-10 00:28 UTC
Labels: closed/duplicate
