### ISSUE TITLE
Same result when using name and partial name on data.octopusdeploy_tenants

### ISSUE THREAD

**Issue by ericlundmark** [OctopusDeployLabs/terraform-provider-octopusdeploy#360] opened 2022-03-25 13:57 UTC
**Describe the bug**

**Steps to reproduce**
1. Create a tenant named Something_Common_Something
2. Create a tenant named Common
3. Use octopusdeploy_tenants with name=common
4. Run
5. You should see both tenants returned in the result, 

**Expected behavior**
There should only be one named common

**Environment and versions:**
- OS: Windows
- Octopus Server Version: 2021.3
- Terraform Version: 0.15.3
- Octopus Terraform Provider Version: 0.7.69

**Comment by johnsimons** [comment] 2022-03-28 04:33
@slewis74 @domenicsim1 I remember you looking into this issue before, this seems to be an issue with the Server API where `name` does a wildcard search too!
Should I raise an issue for Octopus Server?

**Comment by johnsimons** [comment] 2022-03-28 04:34
The issue is that both:
- `/api/Spaces-1/tenants?partialName=And`
- `/api/Spaces-1/tenants?name=And`
 
do a wildcard search 😢

**Comment by johnsimons** [comment] 2022-03-28 04:40
I have raised https://github.com/OctopusDeploy/Issues/issues/7449

**Comment by mjhilton** [comment] 2024-09-10 00:37
As this is being tracked as an issue against Octopus Server and doesn't require any changes to the Terraform Provider, I'm closing this.

I have bumped the Octopus Server issue internally for reprioritisation, given the impact it has on this problem in the Provider. Please watch the Server issue for updates on when this problem gets fixed, and which version of Server the fix lands in.

**Closed by mjhilton** 2024-09-10 00:37 UTC
