### ISSUE TITLE
Template block on project resource throws API error

### ISSUE THREAD

**Issue by ecca** [OctopusDeployLabs/terraform-provider-octopusdeploy#287] opened 2021-12-06 16:02 UTC
**Describe the bug**
When trying to create a **template** block on the **project** resource, Octopus API throws an error message and prevents project variable template from being created.

**Steps to reproduce**
1. Create a terraform file containing following
```terraform
resource "octopusdeploy_project" "project" {
  name                              = "TestProject"
  lifecycle_id                      = "Lifecycles-123"
  space_id                          = "Spaces-1"
  tenanted_deployment_participation = "Tenanted"

  template {
    name = "test"
  }
}
```
2. Terraform apply

**Expected behavior**
Terraform provider should create a project variable template.

**Logs and other supporting information**
```bash
│ Error: Octopus API error: The SpaceId field is required. [] 
│
│   with module.messagedeliveryservice_project.octopusdeploy_project.project,
│   on ..\..\modules\octopusdeploy\project\main.tf line 1, in resource "octopusdeploy_project" "project":
│    1: resource "octopusdeploy_project" "project" {
```

**Environment and versions:**
- OS: Windows
- Octopus Server Version: 2021.3 (Build 8815) - Cloud Version
- Terraform Version: 1.0.11
- Octopus Terraform Provider Version: 0.7.63

**Comment by slewis74** [comment] 2022-01-12 06:31
This looks to be caused by the same bug in the Project schema as #294, so should be resolved by #310

**Closed by slewis74** 2022-01-12 06:31 UTC
