### ISSUE TITLE
Returned id of variableset resources is wrong

### ISSUE THREAD

**Issue by mr-miles** [OctopusDeployLabs/terraform-provider-octopusdeploy#483] opened 2023-02-11 16:23 UTC
**Describe the bug**
The id of a variableset created by terraform is returned with a "variableset-" prefix.  This means 

**Steps to reproduce**

Discovered when looking at the plan with terraform like this:

```
resource "octopusdeploy_library_variable_set" "vs" {
  name        = "VS"
  description = "DESC"
}

resource "octopusdeploy_project" "octopus_basic_project" {
  name             = var.project_name
  lifecycle_id     = var.octopus_lifecycle_id
  project_group_id = var.project_group_id

  included_library_variable_sets = [ octopusdeploy_library_variable_set.vs.id ]
}

```

**Expected behavior**
Expect to use the id as-is to attach a variable set

**Environment and versions:**
- OS: "Linux"
- Octopus Server Version: "202201"
- Terraform Version: 1.3
- Octopus Terraform Provider Version: 0.10.1

**Comment by mjhilton** [comment] 2024-09-10 04:52
This looks to have been fixed since the report. I've just tried to repro using the provided config on version 0.30.2, and all went well:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_library_variable_set.vs will be created
  + resource "octopusdeploy_library_variable_set" "vs" {
      + description     = "DESC"
      + id              = (known after apply)
      + name            = "VS"
      + space_id        = (known after apply)
      + template_ids    = (known after apply)
      + variable_set_id = (known after apply)
    }

  # octopusdeploy_project.octopus_basic_project will be created
  + resource "octopusdeploy_project" "octopus_basic_project" {
      + auto_create_release                  = (known after apply)
      + default_guided_failure_mode          = (known after apply)
      + default_to_skip_if_already_installed = (known after apply)
      + deployment_changes_template          = (known after apply)
      + deployment_process_id                = (known after apply)
      + discrete_channel_release             = (known after apply)
      + id                                   = (known after apply)
      + included_library_variable_sets       = [
          + (known after apply),
        ]
      + is_disabled                          = (known after apply)
      + is_discrete_channel_release          = (known after apply)
      + is_version_controlled                = (known after apply)
      + lifecycle_id                         = "Lifecycles-2"
      + name                                 = "VariableSet Test"
      + project_group_id                     = "ProjectGroups-462"
      + release_notes_template               = (known after apply)
      + slug                                 = (known after apply)
      + space_id                             = (known after apply)
      + tenanted_deployment_participation    = (known after apply)
      + variable_set_id                      = (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_library_variable_set.vs: Creating...
octopusdeploy_library_variable_set.vs: Creation complete after 0s [id=LibraryVariableSets-341]
octopusdeploy_project.octopus_basic_project: Creating...
octopusdeploy_project.octopus_basic_project: Creation complete after 1s [id=Projects-1281]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Closing as unable to reproduce, or fixed since reporting.

**Closed by mjhilton** 2024-09-10 04:52 UTC
Labels: closed/invalid
