### ISSUE TITLE
 Team resourse and user management

### ISSUE THREAD

**Issue by ayupakhomov** [OctopusDeployLabs/terraform-provider-octopusdeploy#125] opened 2021-01-28 09:47 UTC
Hi! Is it possible to manage Teams with this provider, such as Create Team and Add User to a team? 
Is it possible to set an Octa identity to a user?

**Comment by jbristowe** [comment] 2021-01-29 07:35
I've published a new release (v0.7.5) which adds support for teams; specifically, support for a team data source and a team resource. Documentation is included on the [registry page for the provider](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs).

**Comment by ayupakhomov** [comment] 2021-01-29 10:22
Thanks for the fast response!

I am trying to modify users in an existing team in a test environment:

resource "octopusdeploy_team" "teams-spacemanagers-Spaces-1" {
  id = "teams-spacemanagers-Spaces-1"
  name = "Space Managers"
  users = ["Users-23","Users-21"]
 }

As shown, I set the id of an existing team.
When I do terraform apply, I see: 
id = (known after apply)
and instead of modifying a team the new one is created.

Is it the expected behavior? Thanks!

**Comment by ray-jam** [comment] 2021-01-29 11:28
That is standard terraform behaviour, it will always try and create resources and then stores the information in its state file.

If you want existing resources to be managed by terraform then you need to import them : https://www.terraform.io/docs/cli/import/index.html

**Comment by jbristowe** [comment] 2021-01-29 23:35
@ray-jam is correct; this is the expected behaviour of Terraform. Generally, you should NOT modify IDs since they auto-generated and managed by Octopus. They are also the only way of reconciling resources with your state. If they are modified and don't reflect the values in Octopus, Terraform will treat them as *new* resources to create.

**Comment by jbristowe** [comment] 2021-02-05 21:46
Hey @ayupakhomov, would it be OK to close this issue? Or, is there anything else you need help with?

**Comment by ayupakhomov** [comment] 2021-02-07 05:09
Yes, of course.

**Closed** 2021-02-07 21:52 UTC
Labels: enhancement
