### ISSUE TITLE
Terraform plan crash for octopus resources. Error: copy destination is invalid

### ISSUE THREAD

**Issue by osipovdaniil** [OctopusDeployLabs/terraform-provider-octopusdeploy#199] opened 2021-06-18 09:07 UTC
**Describe the bug**
We have to many octopus accounts and deployment targets in our octopus server. After upgrade octopus server from `2020.6.4974` to version `2021.1.7316` we got crash terraform plan with message: `Error: copy destination is invalid`.

**Steps to reproduce**
For reproduce i created [github repo](https://github.com/osipovdaniil/osipov-test-terraform-bug)

**Expected behavior**
Terraform plan don't have errors

**Logs and other supporting information**
See [Github actions](https://github.com/osipovdaniil/osipov-test-terraform-bug/runs/2856689784?check_suite_focus=true)

**Screenshots**

**Environment and versions:**
- OS: Octopus server run on windows OS
- Octopus Server Version: ['2021.1.7316']
- Terraform Version: [`0.13.2`]
- Octopus Terraform Provider Version: ['0.7.37`]

**Additional context**
I would be very grateful for any information on this matter :)

**Comment by jbristowe** [comment] 2021-06-20 23:31
Hey @osipovdaniil! 👋 Thank you for submitting this issue. I am conducting an investigation.

The error, `Error: copy destination is invalid` comes from a dependent library, [copier](https://github.com/jinzhu/copier). This library is used in [go-octopusdeploy](https://github.com/OctopusDeploy/go-octopusdeploy) to convert accounts, endpoints, and worker pools. I am investigating why this error is being generated; it appears to occur for certain token accounts that have been configured in your HCL.

**Comment by eugenberend** [comment] 2021-06-25 11:45
Hi @jbristowe, how can I update the copier library in order to use it with the octopusdeploy provider?

**Comment by osipovdaniil** [comment] 2021-06-29 06:27
Hi @jbristowe . Any news on this issue? I still got a problem

**Comment by jbristowe** [comment] 2021-07-16 22:02
Update: tracing HTTP requests has revealed behaviour that may explain why this issue is occurring. In short, response bodies from `/api/accounts/{id}` can differ between identical requests. This is invalidating the state that's persisted by Terraform. Subsequent comparisons of state is what's causing the copier library to blow up. I am working to discover the case(s) where this behaviour is occurring.

**Comment by jbristowe** [comment] 2021-07-20 00:08
Workaround: reducing the number of accounts being created in batches (i.e. 10 accounts) should resolve this behaviour.

**Comment by stalmok** [comment] 2021-07-20 18:15
Another workaround: use `--refresh=false` if you're sure you have no remote changes.

**Comment by osipovdaniil** [comment] 2021-07-28 06:47
I set '-parallelism=1' in terraform plan and apply. It's helped for me.
Thanks for help guys!

**Comment by stalmok** [comment] 2021-07-28 20:25
I don't think we should close this as it's still an issue. Setting `-parallelism=1` is a good workaround, but now my planning/applying takes forever.

**Comment by jbristowe** [comment] 2021-07-28 21:41
I agree; keeping this issue open will allow us to track it. However, I do not have a solution to this problem at the moment. I will continue to investigate it.

**Comment by stalmok** [comment] 2021-09-30 20:09
Any update on this? I could try to submit a PR if you nudge me in a right direction.

**Comment by jbristowe** [comment] 2021-09-30 20:24
@stalmok Unfortunately, no. The issue exists in the Octopus REST API; there's a concurrency issue that results in the behaviour described by OP. The workaround (above) resolves it.

**Comment by stalmok** [comment] 2021-09-30 21:12
Yeah I've been using that workaround for a while now, but with 1000 resources it's painfully slow. Is there an issue you could point me to in RESP API repo?

**Comment by darren-mcdonald** [comment] 2021-12-10 12:18
I'm also finding this issue. The parallelism=1 workaround works but is tedious when there is many resources to create. I can say that in my example the only octo resource I am trying to manage is multiple octopusdeploy_azure_service_principal.

**Comment by johnsimons** [comment] 2023-02-22 05:17
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 05:17 UTC
Labels: kind/bug
