### ISSUE TITLE
Properties for deploy_package_action action_templates

### ISSUE THREAD

**Issue by angusmcdonald** [OctopusDeployLabs/terraform-provider-octopusdeploy#196] opened 2021-06-10 22:46 UTC
**Is your feature request related to a problem? Please describe.**
The Deprecation of the properties object in deploy_package_action, will stop us from be able to use our custom MSI deploy steps

**Describe the solution you'd like**
An alternative inside action template, or in deploy_package_action

**Describe alternatives you've considered**

**Additional context**
below is an example step that requires the   
**properties //varibles for CustomMSITemplate** 
```
step {
      name = "Example"
      start_trigger = "StartWithPrevious"
      condition     = "Always"
      target_roles = ["Project"]
      deploy_package_action  {
        name        =  "Example"
        properties = { //varibles for CustomMSITemplate 
          "ProjectName" = "Project"
          "InstallationFolder" = "#{MSIStageingPath}"
          "ConfigName" = "#{MSTTransformNameBizTalk}"
          "ProductID" = "Project"
          "PackageID" = "#{BRANCH}.PACK.OC.Project"
        }
        primary_package {
          package_id = "#{BRANCH}.PACK.OC.Project"
        }
        action_template {
          id = "ActionTemplates-3" //CustomMSITemplate 
        }
        
      }
```

**Comment by johnsimons** [comment] 2023-02-22 06:46
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 06:46 UTC
Labels: area/actions
