### ISSUE TITLE
Unable to create Cloud Regions

### ISSUE THREAD

**Issue by OmarSalka** [OctopusDeployLabs/terraform-provider-octopusdeploy#128] opened 2021-02-02 17:44 UTC
I tried creating a cloud region using "octopusdeploy_deployment_target" and "octopusdeploy_cloud_region_deployment_target", but no use. I even used the data resource "octopusdeploy_cloud_region_deployment_targets" to copy all the returned attributes from a manually created Cloud Region and still no use. 

I am getting the following error: **_Error: Octopus API error: Value cannot be null. Parameter name: source []_** 

Example code:

```
resource "octopusdeploy_cloud_region_deployment_target" "test" {
   name                                                 = "test"
   environments                                    = [octopusdeploy_environment.test.id]
   roles                                                  = ["TEST"]
   default_worker_pool_id                     = "WorkerPools-100"
   tenanted_deployment_participation = "Untenanted"
    endpoint {
      communication_style = "None"
    }
 }
```

**Comment by jbristowe** [comment] 2021-02-03 04:34
I cannot reproduce this behaviour on my end. I suspect the reference, `octopusdeploy_environment.test.id` is `null`. This would generate the response you're seeing from Octopus API. Please confirm.

**Comment by jbristowe** [comment] 2021-02-05 21:41
Hey @OmarSalka, were you able to confirm the value of `octopusdeploy_environment.test.id`?

**Comment by OmarSalka** [comment] 2021-02-08 18:27
It’s returning the environment ID as expected, I also verified using a terraform output value.

**Comment by OmarSalka** [comment] 2021-02-08 18:47
I even hardcoded the environment id and it's still returning the same error

**Comment by OmarSalka** [comment] 2021-02-08 18:55
I even added gibberish and it's still returning the "**_Value cannot be null. Parameter name: source []_**" error

```
resource "octopusdeploy_cloud_region_deployment_target" "test" {
  name                            = "test-new-od-tf-provider"
  environments                    = ["afasfaf"]
  roles                           = ["INFRA"]
}
```

**Comment by OmarSalka** [comment] 2021-02-09 13:28
When i comment out everything...
```
resource "octopusdeploy_cloud_region_deployment_target" "test" {
  # name                            = "test-new-od-tf-provider"
  # environments                    = [octopusdeploy_environment.test.id]
  # roles                           = ["INFRA"]
  # default_worker_pool_id          = "WorkerPools-41"
}
```
... it returns this error 
```
Error: Missing required argument

  on test_od.tf line 20, in resource "octopusdeploy_cloud_region_deployment_target" "test":
  20: resource "octopusdeploy_cloud_region_deployment_target" "test" {

The argument "name" is required, but no definition was found.
```

**Comment by OmarSalka** [comment] 2021-02-09 13:53
Here are some trace logs
```
2021-02-09T07:41:03.033-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.7.10.exe: 2021/02/09 07:41:03 [INFO] reading environment (Environments-888): timestamp=2021-02-09T07:41:03.032-0600
2021/02/09 07:41:03 [TRACE] GRPCProvider: PlanResourceChange
octop2021/02/09 07:41:03 [WARN] Provider "registry.terraform.io/octopusdeploylabs/octopusdeploy" produced an invalid plan for octopusdeploy_cloud_region_deployment_target.test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .tenanted_deployment_participation: planned value cty.StringVal("Untenanted") does not match config value cty.NullVal(cty.String)
      - .endpoint: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
2021/02/09 07:41:03 [TRACE] eval: *terraform.EvalWriteState
2021/02/09 07:41:03 [TRACE] EvalWriteState: recording 0 dependencies for octopusdeploy_cloud_region_deployment_target.test
2021/02/09 07:41:03 [TRACE] EvalWriteState: writing current state object for octopusdeploy_cloud_region_deployment_target.test
2021/02/09 07:41:03 [TRACE] eval: *terraform.EvalWriteDiff
```

```
2021/02/09 07:41:03 [WARN] Provider "registry.terraform.io/octopusdeploylabs/octopusdeploy" produced an invalid plan for octopusdeploy_cloud_region_deployment_target.test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .tenanted_deployment_participation: planned value cty.StringVal("Untenanted") does not match config value cty.NullVal(cty.String)
      - .endpoint: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
2021/02/09 07:41:03 [TRACE] eval: *terraform.EvalCheckPreventDestroy
2021/02/09 07:41:03 [TRACE] eval: *terraform.EvalWriteState
2021/02/09 07:41:03 [TRACE] EvalWriteState: writing current state object for octopusdeploy_cloud_region_deployment_target.test
```
```
2021/02/09 07:41:03 [TRACE] eval: *terraform.EvalCloseProvider
2021/02/09 07:41:03 [TRACE] GRPCProvider: Close
2021/02/09 07:41:03 [TRACE] [walkPlan] Exiting eval tree: meta.count-boundary (EachMode fixup)
2021/02/09 07:41:03 [TRACE] vertex "meta.count-boundary (EachMode fixup)": visit complete
2021-02-09T07:41:03.532-0600 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-09T07:41:03.544-0600 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/octopusdeploylabs/octopusdeploy/0.7.10/windows_amd64/terraform-provider-octopusdeploy_v0.7.10.exe pid=24224
2021-02-09T07:41:03.544-0600 [DEBUG] plugin: plugin exited
2021/02/09 07:41:03 [TRACE] [walkPlan] Exiting eval tree: provider["registry.terraform.io/octopusdeploylabs/octopusdeploy"] (close)
2021/02/09 07:41:03 [TRACE] vertex "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"] (close)": visit complete
2021/02/09 07:41:03 [TRACE] dag/walk: visiting "root"
2021/02/09 07:41:03 [TRACE] vertex "root": starting visit (*terraform.nodeCloseModule)
2021/02/09 07:41:03 [TRACE] vertex "root": evaluating
```
```
2021/02/09 07:41:03 [DEBUG] octopusdeploy_cloud_region_deployment_target.test: applying the planned Create change
2021/02/09 07:41:03 [TRACE] GRPCProvider: ApplyResourceChange
2021-02-09T07:41:03.942-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.7.10.exe: 2021/02/09 07:41:03 [DEBUG] setting computed for "tenant_tags" from ComputedKeys: timestamp=2021-02-09T07:41:03.941-0600
octopusdeploy_cloud_reg2021-02-09T07:41:03.942-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.7.10.exe: 2021/02/09 07:41:03 [DEBUG] setting computed for "endpoint" from ComputedKeys: timestamp=2021-02-09T07:41:03.941-0600
2021-02-09T07:41:03.942-0600 [INFO]  plugin.terraform-provider-octopusdeploy_v0.7.10.exe: 2021/02/09 07:41:03 [INFO] creating cloud region deployment target: &octopusdeploy.DeploymentTarget{EnvironmentIDs:[]string{"afasfaf", "asfasfS"}, Roles:[]string{"INFRA"}, SpaceID:"", TenantedDeploymentMode:"Untenanted", TenantIDs:[]string(nil), TenantTags:[]string(nil), machine:octopusdeploy.machine{Endpoint:(*octopusdeploy.CloudRegionEndpoint)(0xc000591360), HasLatestCalamari:false, HealthStatus:"", IsDisabled:false, IsInProcess:false, MachinePolicyID:"", Name:"test-new-od-tf-provider", OperatingSystem:"Unknown", ShellName:"Unknown", ShellVersion:"Unknown", Status:"", StatusSummary:"", Thumbprint:"", URI:"", resource:octopusdeploy.resource{ID:"", ModifiedBy:"", ModifiedOn:(*time.Time)(nil), Links:map[string]string{}}}}: timestamp=2021-02-09T07:41:03.941-0600
ion_deployment_target.test: Creating...
2021/02/09 07:41:04 [DEBUG] octopusdeploy_cloud_region_deployment_target.test: apply errored, but we're indicating that via the Error pointer rather than returning it: Octopus API error: Value cannot be null.
Parameter name: source []
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalMaybeTainted
2021/02/09 07:41:04 [TRACE] EvalMaybeTainted: octopusdeploy_cloud_region_deployment_target.test encountered an error during creation, so it is now marked as tainted
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalWriteState
2021/02/09 07:41:04 [TRACE] EvalWriteState: removing state object for octopusdeploy_cloud_region_deployment_target.test
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalApplyProvisioners
2021/02/09 07:41:04 [TRACE] EvalApplyProvisioners: octopusdeploy_cloud_region_deployment_target.test has no state, so skipping provisioners
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalMaybeTainted
2021/02/09 07:41:04 [TRACE] EvalMaybeTainted: octopusdeploy_cloud_region_deployment_target.test encountered an error during creation, so it is now marked as tainted
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalWriteState
2021/02/09 07:41:04 [TRACE] EvalWriteState: removing state object for octopusdeploy_cloud_region_deployment_target.test
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalIf
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalIf
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalWriteDiff
2021/02/09 07:41:04 [TRACE] eval: *terraform.EvalApplyPost
2021/02/09 07:41:04 [ERROR] eval: *terraform.EvalApplyPost, err: Octopus API error: Value cannot be null.
Parameter name: source []
2021/02/09 07:41:04 [ERROR] eval: *terraform.EvalSequence, err: Octopus API error: Value cannot be null.
Parameter name: source []
2021/02/09 07:41:04 [TRACE] [walkApply] Exiting eval tree: octopusdeploy_cloud_region_deployment_target.test
2021/02/09 07:41:04 [TRACE] vertex "octopusdeploy_cloud_region_deployment_target.test": visit complete
2021/02/09 07:41:04 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/09 07:41:04 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"] (close)" errored, so skipping
2021/02/09 07:41:04 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/02/09 07:41:04 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2021/02/09 07:41:04 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2021/02/09 07:41:04 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/02/09 07:41:04 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info

Error: 2021/02/09 07:41:04 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
Octopus API error: Value cannot be nu2021-02-09T07:41:04.039-0600 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
ll.
Parameter name: source [] 


2021-02-09T07:41:04.049-0600 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/octopusdeploylabs/octopusdeploy/0.7.10/windows_amd64/terraform-provider-octopusdeploy_v0.7.10.exe pid=12908
2021-02-09T07:41:04.049-0600 [DEBUG] plugin: plugin exited
```

**Comment by jbristowe** [comment] 2021-02-09 20:17
Thanks for this information! I'll take a look.

**Comment by OmarSalka** [comment] 2021-02-12 13:35
@jbristowe any updates on this? btw I forgot to mention we're using an on-prem Octopus Deploy Server v2019.6.3 LTS

**Comment by OmarSalka** [comment] 2021-02-12 17:09
I don't run into this issue with the old Octopus Deploy terraform provider https://registry.terraform.io/providers/petelopez/octopusdeploy/latest

**Comment by OmarSalka** [comment] 2021-02-12 17:15
I am getting the same error when trying to create a cloud region through the "octopusdeploy_deployment_target" resource
```
resource "octopusdeploy_deployment_target" "test" {
  name                            = "test-new-od-tf-provider"
  environments                    = [octopusdeploy_environment.test.id]
  roles                           = ["INFRA"]
  endpoint {
    communication_style = "None"
  }
}
```

**Comment by jbristowe** [comment] 2021-02-12 18:56
> @jbristowe any updates on this? btw I forgot to mention we're using an on-prem Octopus Deploy Server v2019.6.3 LTS

Ah, I didn't realise you were using an older version. I haven't tested the Terraform Provider against instances older than 2020.4.*. Nevertheless, I am looking into this.

I suspect the reason for this error will be simple. There's a validation that's failing in the API when it receives the `POST` from the client. It may be something trivial like the `tenant ID` is `null` or something like that. The problem at the moment is the error log you provided isn't telling me which property is failing validation.

At the moment, I'm looking into the validation checks that we perform in the API, looking to see what's changed over the past couple of years.

I'll keep you posted.

**Comment by OmarSalka** [comment] 2021-02-25 21:07
@jbristowe any updates on this?

**Comment by jbristowe** [comment] 2021-03-11 01:49
Just a quick follow up on this...

Here's the configuration that should work:

```
resource "octopusdeploy_cloud_region_deployment_target" "test" {
  name                              = "test"
  environments                      = [octopusdeploy_environment.test.id]
  roles                             = ["TEST"]
  default_worker_pool_id            = "WorkerPools-100"
  tenanted_deployment_participation = "Untenanted"
}
```

Please note that you should not specific the `endpoint` with this configuration.

Does this work?

**Comment by OmarSalka** [comment] 2021-03-16 12:56
nope, still seeing the same error

**Comment by johnsimons** [comment] 2023-02-22 03:42
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 03:42 UTC
