### ISSUE TITLE
Using terraform CDK, MachinePolicy creation is failing

### ISSUE THREAD

**Issue by dibya-das** [OctopusDeployLabs/terraform-provider-octopusdeploy#450] opened 2022-10-12 04:17 UTC
**Describe the bug**
I am trying to create an Machine Policy using Terraform CDK, The Plugin keeps crashing when trying to create Machine Policy

**Steps to reproduce**
Create a local docker based Octopus Server by following this Guide.
https://octopus.com/docs/installation/octopus-server-linux-container/docker-compose-linux

Command to start up the Services,
`docker-compose --project-name octopus up -d`
Login to the Octopus Server and create an API Key which will be Required later.

Install CDKTF in machine. Follow Guide: https://learn.hashicorp.com/tutorials/terraform/cdktf-install?in=terraform/cdktf
`$ npm install --global cdktf-cli@latest`

Inside a Blank Directory, Install a Project:
`cdktf init --template=typescript --local`

Add the Provider:
`cdktf provider add OctopusDeployLabs/octopusdeploy`

Add the below code in the main.ts
`import { Construct } from "constructs";
import { App, S3Backend, TerraformStack } from "cdktf";
import { OctopusdeployProvider } from "./.gen/providers/octopusdeploy/provider";

import { MachinePolicy } from "./.gen/providers/octopusdeploy/machine-policy";

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new OctopusdeployProvider(this, "octopusdeploy", {
      address: "http://localhost:8080",
      apiKey: "<API-Key>"
    });

    new MachinePolicy(this, "machinePolicyDefault", {
      name: "machinePolicyDefault"
    });

  }

}
const app = new App();
new MyStack(app, "iac_code");
app.synth();`

Run the Code now which will throw the error:
`cdktf deploy`

**Expected behavior**
Expected Behaviour is to create a blank machine policy.

**Logs and other supporting information**
`PS C:\buildium\src\octopus\iac_code> cdktf deploy
iac_code  Initializing the backend...
iac_code  Initializing provider plugins...
          - Reusing previous version of octopusdeploylabs/octopusdeploy from the dependency lock file
iac_code  - Using previously-installed octopusdeploylabs/octopusdeploy v0.8.1

          Terraform has been successfully initialized!

          You may now begin working with Terraform. Try running "terraform plan" to see  
          any changes that are required for your infrastructure. All Terraform commands  
          should now work.

          If you ever set or change modules or backend configuration for Terraform,      
          rerun this command to reinitialize your working directory. If you forget, other
          commands will detect it and remind you to do so if necessary.

1 Stack deploying     0 Stacks done     0 Stacks waiting
[2022-10-12T09:37:48.130] [ERROR] default - ╷
│ Error: Plugin did not respond
│ 
│   with octopusdeploy_machine_policy.machinePolicyDefault,
│   on cdk.tf.json line 29, in resource.octopusdeploy_machine_policy.machinePolicyDefault:
│   29:       }
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.8.1.exe plugin:

panic: Error reading level config: strconv.ParseInt: parsing "300000000000": value out of range

goroutine 63 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x12cf0a50, {0x13294710, 0x1, 0x1}, 0x12)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x12cf0a50, {0x108c093, 0x1b}, 0x1, 0x12)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:524 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x12cf0a50, {0x108c093, 0x1b})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:501 +0x63
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0x12c931c0, {0x108c093, 0x1b}, 0x12fe7540, 0x12ceb65c, {0x11d0910, 0x12cf0a50}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:1542 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x12c931c0, {0x11ced60, 0x132ebfb0}, {0x108c093, 0x1b}, 0x12fe7540, 0x12cf0a00, {0x11d0910, 0x12cf0a50}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:1124 +0x136
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x12c931c0, {0x11ced60, 0x132ebfb0}, 0x133832d0, 0x12c8a2b8, 0x0, {0xf2f260, 0x1362e140}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:678 +0x2b7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x12fdbdc0, {0x11ced60, 0x132ebfb0}, 0x133832d0, 0x12c8a2b8, {0xf2f260, 0x1362e140})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:890 +0x6f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x12c8dfc0, {0x11ced60, 0x132ebf50}, 0x13384d50)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:741 +0xb64
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0x12c01270, {0x11ced60, 0x132ebc68}, 0x12e7d740)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:780 +0x50b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x10425c0, 0x12c01270}, {0x11ced60, 0x132ebc68}, 0x12e7d6c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x12eb5200, {0x11d13a0, 0x12d10120}, 0x12da0aa0, 0x12c8b488, 0x1769b34, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xaab
google.golang.org/grpc.(*Server).handleStream(0x12eb5200, {0x11d13a0, 0x12d10120}, 0x12da0aa0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x25f

Error: The terraform-provider-octopusdeploy_v0.8.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
iac_code  ╷
          │ Error: Plugin did not respond
          │
          │   with octopusdeploy_machine_policy.machinePolicyDefault (machinePolicyDefault),
          │   on cdk.tf.json line 29, in resource.octopusdeploy_machine_policy.machinePolicyDefault (machinePolicyDefault):
          │   29:       }
          │
          │ The plugin encountered an error, and failed to respond to the
          │ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
          │ more details.
          ╵

          Stack trace from the terraform-provider-octopusdeploy_v0.8.1.exe plugin:

          panic: Error reading level config: strconv.ParseInt: parsing "300000000000": value out of range

          goroutine 63 [running]:
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x12cf0a50, {0x13294710, 0x1, 0x1}, 0x12)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:553 +0x279
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x12cf0a50, {0x108c093, 0x1b}, 0x1, 0x12)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:524 +0x15f
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x12cf0a50, {0x108c093, 0x1b})
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:501 +0x63
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0x12c931c0, {0x108c093, 0x1b}, 0x12fe7540, 0x12ceb65c, {0x11d0910, 0x12cf0a50}, 0x0)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:1542 +0x85
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x12c931c0, {0x11ced60, 0x132ebfb0}, {0x108c093, 0x1b}, 0x12fe7540, 0x12cf0a00, {0x11d0910, 0x12cf0a50}, 0x0)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:1124 +0x136
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x12c931c0, {0x11ced60, 0x132ebfb0}, 0x133832d0, 0x12c8a2b8, 0x0, {0xf2f260, 0x1362e140}, 0x0)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/schema.go:678 +0x2b7
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x12fdbdc0, {0x11ced60, 0x132ebfb0}, 0x133832d0, 0x12c8a2b8, {0xf2f260, 0x1362e140})
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:890 +0x6f
          github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x12c8dfc0, {0x11ced60, 0x132ebf50}, 0x13384d50)
                github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:741 +0xb64
          github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0x12c01270, {0x11ced60, 0x132ebc68}, 0x12e7d740)
                github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:780 +0x50b
          github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x10425c0, 0x12c01270}, {0x11ced60, 0x132ebc68}, 0x12e7d6c0, 0x0)
                github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x18a
          google.golang.org/grpc.(*Server).processUnaryRPC(0x12eb5200, {0x11d13a0, 0x12d10120}, 0x12da0aa0, 0x12c8b488, 0x1769b34, 0x0)
                google.golang.org/grpc@v1.48.0/server.go:1295 +0xaab
          google.golang.org/grpc.(*Server).handleStream(0x12eb5200, {0x11d13a0, 0x12d10120}, 0x12da0aa0, 0x0)
                google.golang.org/grpc@v1.48.0/server.go:1636 +0xa17
          google.golang.org/grpc.(*Server).serveStreams.func1.2()
                google.golang.org/grpc@v1.48.0/server.go:932 +0xb1
          created by google.golang.org/grpc.(*Server).serveStreams.func1
                google.golang.org/grpc@v1.48.0/server.go:930 +0x25f

          Error: The terraform-provider-octopusdeploy_v0.8.1.exe plugin crashed!

          This is always indicative of a bug within the plugin. It would be immensely
          helpful if you could report the crash with the plugin's maintainers so that it
          can be fixed. The output above should help diagnose the issue.

iac_code

1 Stack deploying     0 Stacks done     0 Stacks waiting
non-zero exit code 1`

**Screenshots**
![image](https://user-images.githubusercontent.com/93909026/195248990-609d9d39-524d-4f70-b4be-07cd8d8addbd.png)
![image](https://user-images.githubusercontent.com/93909026/195249056-4cbf05ef-861c-4557-abf3-2613109ac069.png)

**Environment and versions:**
- OS: `Windows`
- Octopus Server Version:  `2022.3`
- Terraform Version:  `1.2.5`
- Octopus Terraform Provider Version:  `0.8.1`

**Additional Context**
I was able to add all kind of things using the CDK, so far, project, variable, lifecycle, worker pool, project group, environments, library set, Only while creating the Machine Policy its failing.

The Actual Machine policy i was using was bigger in context, just to remove the all external factors, i kept this above code to bare minimum, but it still fails off.

**Comment by johnsimons** [comment] 2023-02-22 05:55
I was not able to reproduce this issue using v0.10.3.
I did the following using terraform.
```tf
resource "octopusdeploy_machine_policy" "hello" {
  name = "hello"
}
```

I know this is not using the cdk but I assume it ends up being the same.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 05:55 UTC
