### ISSUE TITLE
Add a resource for creating Step Templates

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#145] opened 2021-03-26 19:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently, defining and managing step templates is unsupported. (For ability to **consume** Step Templates in Deployment Processes, see #137)

As a user, I would like to have them supported by the Terraform Provider for Octopus Deploy so that I may manage them through configuration with Terraform.

**Describe the solution you'd like**
A new resource (i.e. `octopusdeploy_step_template`) that provides an ability to create, update and destroy Step Templates through configuration with Terraform.

**Describe alternatives you've considered**
No alternatives are available at the moment.

**Additional context**
This request was originally made by a member of the Octopus Deploy Community Slack.

**Comment by ajaychoudhary-bcg** [comment] 2021-04-01 08:35
do we know by when it will be available?

**Comment by ajaychoudhary-bcg** [comment] 2021-08-12 10:20
Any update on this?

**Comment by DamienDaco** [comment] 2021-09-01 08:16
I would also like to know if step templates will be supported in the future, cheers.

**Comment by k0kazpt** [comment] 2022-07-14 08:30
This would be a great feature, as most deployment processes use step templates. Currently the only way I know around this is to call the API directly using a null resource.

**Comment by tdeblsh** [comment] 2022-12-21 06:30
Would be really appreciated

**Comment by Scott-Emberson** [comment] 2023-11-13 10:37
@jbristowe any idea when this feature could be available?

**Comment by zentron** [comment] 2024-04-22 10:21
Closing as duplicate of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/137

**Closed** 2024-10-16 01:26 UTC
Labels: kind/enhancement, area/deployment-processes
