### ISSUE TITLE
[Feature] action_templates to be able to create/update Step Templates

### ISSUE THREAD

**Issue by lee5i3** [OctopusDeployLabs/terraform-provider-octopusdeploy#588] opened 2023-12-13 20:14 UTC
We want to be able to use the same step template across spaces and we'd like to be able to manage this through terraform, we can currently do this with a bash script

Using CURL
```
curl -X POST "http://your-octopus-server/api/actiontemplates" \
     -H "X-Octopus-ApiKey: YOUR_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{
            "Name": "My Custom Step",
            "Description": "This is a custom step for deploying a specific component",
            "ActionType": "Octopus.Script",
            "Version": 0,
            "Properties": {
                "Octopus.Action.Script.Syntax": "PowerShell",
                "Octopus.Action.Script.ScriptBody": "Write-Host \"Hello from my custom step!\""
            },
            "Parameters": [
                {
                    "Name": "Parameter1",
                    "Label": "My First Parameter",
                    "HelpText": "This is a parameter used by the custom step.",
                    "DefaultValue": "",
                    "DisplaySettings": {
                        "Octopus.ControlType": "SingleLineText"
                    }
                }
            ]
         }'
```

We'd like to be able to do something like this

```
resource "octopusdeploy_action_template" "my_custom_step" {
  name        = "My Custom Step"
  description = "This is a custom step for deploying a specific component"
  space_id = "Space-1"
  action_type = "Octopus.Script"
  properties {
    syntax = "PowerShell"
    script_body = "Write-Host Hello"
  }

  parameter {
      name = "Parameter1"
      label = "My Parameter"
      default_value = ""
  }
}
```

**Comment by eternalapprentice2000** [comment] 2023-12-19 16:19
+1 this is something my team has been needing for a while.

**Comment by eternalapprentice2000** [comment] 2023-12-19 18:40
for the time being I am using the `restapi` terraform module.  You can see a working example POC i created to help you through.  

https://github.com/kennethgarza/terraform-script-module-null-resource-poc

**Comment by andrew22224** [comment] 2024-01-03 22:42
+1

**Comment by zentron** [comment] 2024-04-22 21:46
Duplicate of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/137

**Comment by x-sajalshres** [comment] 2024-07-04 02:33
+1

**Comment by mjhilton** [comment] 2024-09-13 05:25
Duplicate of #145

**Closed by mjhilton** 2024-09-13 05:25 UTC
Labels: kind/enhancement
