### ISSUE TITLE
For Deployment Process, mixing action steps fail on reapply

### ISSUE THREAD

**Issue by paypalghegawa** [OctopusDeployLabs/terraform-provider-octopusdeploy#457] opened 2022-10-27 18:53 UTC
**Describe the bug**
adding a different step action before or after causes failure with the error [Action name '$ACTION_NAME' is already in use by another action in this deployment process. Action names must be unique. Actions names '$ACTION_NAME', '$ANOTHER_ACTION_NAME' are already in use by other steps in this deployment process. Action names must be unique.]

**Steps to reproduce**

**Scenario 1: use the new action method**
1. Start with run_script_action, deploy_package_action, and manual_intervention_action
```terraform
# Apply First.  Add any run_script_action in between and it will fail
resource "octopusdeploy_deployment_process" "octopus_deployment_process" {
  project_id = octopusdeploy_project.octopus_project.id
  step {
    condition           = "Success"
    name                = "Bash Script"
    target_roles        = var.target_roles
    package_requirement = "LetOctopusDecide"
    run_script_action {
      name          = "Bash Script"
      features      = []
      run_on_server = false
      script_syntax = "Bash"
      script_body   = <<-EOT
          echo "Bash Script"
        EOT
    }
  }
  step {
    condition     = "Success"
    name          = "Deploy Package"
    target_roles  = var.target_roles
    start_trigger = "StartAfterPrevious"
    deploy_package_action {
      name     = "Deploy Package"
      features = ["Octopus.Features.SubstituteInFiles", "Octopus.Features.CustomDirectory"]
      primary_package {
        package_id           = var.package_name
        feed_id              = var.id
        acquisition_location = "Server"
      }
      properties = {
        "Octopus.Action.Package.CustomInstallationDirectory"                               = "/some_directory/"
        "Octopus.Action.Package.CustomInstallationDirectoryShouldBePurgedBeforeDeployment" = "True"
        "Octopus.Action.SubstituteInFiles.TargetFiles"                                     = "*.tf"
      }
    }
  }
  step {
    condition     = "Success"
    name          = "Manual Intervention"
    target_roles  = var.target_roles
    start_trigger = "StartAfterPrevious"
    manual_intervention_action {
      name              = "Manual Intervention"
      instructions      = "some instruction"
      is_required       = true
      responsible_teams = data.octopusdeploy_teams.octopus_team.teams[0].id
      environments      = []
    }
  }
}
```
2. add any run_script_action in between the steps above

**Scenario 2: Doing everything as "action"**
1. start with all actions with "action_type" of Octopus.Script and Octopus.Tentacle.Package
```terraform
# Apply First.  Add any "Octopus.Script" and it will fail

resource "octopusdeploy_deployment_process" "octopus_deployment_process" {
  project_id = octopusdeploy_project.octopus_project.id
  step {
    condition           = "Success"
    name                = "Create Working Directory"
    target_roles        = var.target_roles
    package_requirement = "LetOctopusDecide"
    action {
      action_type = "Octopus.Script"
      name        = "Create Working Directory"
      properties  = {
        "Octopus.Action.Script.ScriptBody"   = <<-EOT
          mkdir -p get_octopusvariable "${var.install_directory}"
        EOT
        "Octopus.Action.Script.ScriptSource" = "Inline"
        "Octopus.Action.Script.Syntax"       = "Bash"
      }
      run_on_server = false
    }
  }
    step {
      condition     = "Success"
      name          = "Download Package to Working Directory"
      target_roles  = var.target_roles
      start_trigger = "StartAfterPrevious"
      action {
        action_type = "Octopus.TentaclePackage"
        name       = "Download Package to Working Directory"
        features   = ["Octopus.Features.SubstituteInFiles", "Octopus.Features.CustomDirectory"]
        properties = {
          "Octopus.Action.EnabledFeatures"               = "Octopus.Features.CustomInstallationDirectory,Octopus.Features.SubstituteInFiles"
          "Octopus.Action.Package.CustomInstallationDirectory"                               = "#{${var.install_directory}}"
          "Octopus.Action.Package.CustomInstallationDirectoryShouldBePurgedBeforeDeployment" = "True"
          "Octopus.Action.SubstituteInFiles.TargetFiles"                                     = "terraform/*.tfvars\nterraform/*.tf\nterraform/variables/#{Tenant.File.Directory}*.tfvars\nterraform/variables/#{Tenant.File.Directory}*.tf"
          "Octopus.Action.Package.FeedId"                = data.octopusdeploy_feeds.octopus_feed.feeds[0].id
          "Octopus.Action.Package.PackageId"             = var.package_name
          "Octopus.Action.Package.DownloadOnTentacle"    = "True"
        }
      }
    }
  step {
    condition           = "Success"
    name                = "Create Working Directory1"
    target_roles        = var.target_roles
    package_requirement = "LetOctopusDecide"
    action {
      action_type = "Octopus.Script"
      name        = "Create Working Directory1"
      properties  = {
        "Octopus.Action.Script.ScriptBody"   = <<-EOT
          mkdir -p get_octopusvariable "${var.install_directory}"
        EOT
        "Octopus.Action.Script.ScriptSource" = "Inline"
        "Octopus.Action.Script.Syntax"       = "Bash"
      }
      run_on_server = false
    }
  }
  }
```
2. add any Octopus.Script Before or after 

**Expected behavior**
re apply should re-order and add the additional steps

**Logs and other supporting information**
```
octopus deploy api returned an error on endpoint /api/Spaces-NUMBER/projects/Projects-NUMBER/deploymentprocesses - [Action name 'ACTION_NAME' is already in use by another action in this deployment process. Action names must be unique. Actions names 'ACTION_NAME', 'SOME_OTHER_ACTION_NAME' are already in use by other steps in this deployment process. Action names must be unique.]

```

**Environment and versions:**
- OS: [`Linux``]
- Octopus Server Version: [Ubuntu 20.01]
- Terraform Version: [1.3.3]
- Octopus Terraform Provider Version: [ `0.8.1`]

**Additional context**
this bug makes the entire projects resources unusable.  steps are the most complicated portion of an octopus project.

**Comment by briggs-octo** [comment] 2022-10-31 20:49
Similar to / duplicate of [this issue]( https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/445)

**Comment by paypalghegawa** [comment] 2023-01-19 16:23
happy new years. checking on this issue

**Comment by patrick-smergut-octopus** [comment] 2023-01-26 19:53
User reported here [internal]: https://octopus.zendesk.com/agent/tickets/103699

**Comment by zentron** [comment] 2023-04-02 12:28
related TF behavior https://discuss.hashicorp.com/t/typeset-is-not-picking-up-correct-changes/23735/2

**Comment by zentron** [comment] 2023-04-07 00:03
Fixed By: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/510

**Closed** 2023-04-11 03:00 UTC
