### ISSUE TITLE
octopusdeploy_listening_tentacle_deployment_target returns  Parameter name: source [] Value cannot be null

### ISSUE THREAD

**Issue by thcp** [OctopusDeployLabs/terraform-provider-octopusdeploy#162] opened 2021-04-16 12:24 UTC
When trying to add a new deployment target via terraform: 

```
provider "octopusdeploy" {
  address = var.octopus_url
  api_key = var.octopus_api_key
}

resource "octopusdeploy_listening_tentacle_deployment_target" "target" {
  name = "sample-server"
  tentacle_url = "x.x.x.x"
  roles = ["something"]
  thumbprint = var.octopus_thumbprint
}
```

Output:
```
Error: Octopus API error: Value cannot be null.
Parameter name: source [] Value cannot be null.
Parameter name: source
System.ArgumentNullException
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Rules.TenantsFiltersAndTenantedDeploymentParticipationAgreeRule.BeforeMap(IParticipateInTenantedDeployments model, IParticipateInTenantedDeployments resource, ISpecialRuleContext context)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRules[TRule](Action`2 ruleCallback)
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

  on octopus.tf line 14, in resource "octopusdeploy_listening_tentacle_deployment_target" "target":
  14: resource "octopusdeploy_listening_tentacle_deployment_target" "target" {

Releasing state lock. This may take a few moments...

```

The following document was used for reference: https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/listening_tentacle_deployment_target

OS: LInux
Octopus Server Version: 3.15.8
Terraform Version:v0.14.9
Octopus Terraform Provider Version: "0.7.23"

**Comment by jbristowe** [comment] 2021-04-16 20:24
Hey @thcp! 👋 Thanks for submitting this issue.

You are missing a `environments` attribute for the `octopusdeploy_listening_tentacle_deployment_target` resource. It should look something like this:

```
resource "octopusdeploy_listening_tentacle_deployment_target" "target" {
  environments = ["Environments-123"]
  name         = "sample-server"
  tentacle_url = "x.x.x.x"
  roles        = ["something"]
  thumbprint   = var.octopus_thumbprint
}
```

While looking into this issue, I noticed that we're not validating all the requirements necessary for this resource. I have created a new issue to resolve this behaviour.

**Comment by thcp** [comment] 2021-04-16 23:43
Hi @jbristowe  thanks for the feedback, also, i even with the environment set I had the same behaviour.

**Comment by jbristowe** [comment] 2021-04-16 23:47
Hmm, that's interesting. I've released a new version that adds validation to the `octopusdeploy_listening_tentacle_deployment_target` resource. Perhaps the latest version will provide more context. At the moment, it's difficult to determine where the problem lies.

The error (above) mentions an error on line 14. I'm curious to know what your configuration looks like there.

**Comment by thcp** [comment] 2021-04-16 23:55
let me pull the branch and i can paste the info in a minute (also, you dont need to check it right now, i dont want to ruin your friday night :) )

**Comment by jbristowe** [comment] 2021-04-17 00:25
Listening tentacles require a secure channel for communication. From [Octopus - Tentacle Communication](https://octopus.com/docs/security/octopus-tentacle-communication):

> Regardless of whether Tentacle is in listening mode or polling mode, all communication between the Tentacle and Octopus is performed over a secure (TLS) connection.

If you don't specify an `https://` scheme for the tentacle URL, the Octopus API will return an error. I've simply added validation to the provider to ensure that this scheme is specified in the configuration.

**Comment by thcp** [comment] 2021-04-18 00:09
thanks for the information @jbristowe , now, with the new version I'm getting:


```
 % tf14 apply --target=octopusdeploy_listening_tentacle_deployment_target.target
octopusdeploy_environment.octopus: Refreshing state... [id=Environments-501]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_listening_tentacle_deployment_target.target will be created
  + resource "octopusdeploy_listening_tentacle_deployment_target" "target" {
      + certificate_signature_algorithm   = (known after apply)
      + environments                      = [
          + "xx",
        ]
      + has_latest_calamari               = (known after apply)
      + health_status                     = (known after apply)
      + id                                = (known after apply)
      + is_disabled                       = true
      + is_in_process                     = (known after apply)
      + machine_policy_id                 = (known after apply)
      + name                              = "sample-server"
      + operating_system                  = (known after apply)
      + proxy_id                          = (known after apply)
      + roles                             = [
          + "xx",
        ]
      + shell_name                        = (known after apply)
      + shell_version                     = (known after apply)
      + space_id                          = (known after apply)
      + status                            = (known after apply)
      + status_summary                    = (known after apply)
      + tenant_tags                       = (known after apply)
      + tenanted_deployment_participation = "Untenanted"
      + tentacle_url                      = "https://xxx:10933"
      + thumbprint                        = "xxx"
      + uri                               = (known after apply)

      + tentacle_version_details {
          + upgrade_locked    = (known after apply)
          + upgrade_required  = (known after apply)
          + upgrade_suggested = (known after apply)
          + version           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.


Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.

The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.

Do you want to perform these actions in workspace "we-prd"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_listening_tentacle_deployment_target.target: Creating...

Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan

Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Error: Octopus API error: Value cannot be null.
Parameter name: source [] Value cannot be null.
Parameter name: source
System.ArgumentNullException
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Octopus.Server.Web.Api.Rules.TenantsFiltersAndTenantedDeploymentParticipationAgreeRule.BeforeMap(IParticipateInTenantedDeployments model, IParticipateInTenantedDeployments resource, ISpecialRuleContext context)
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.ExecuteRules[TRule](Action`2 ruleCallback)
   at Octopus.Server.Web.Infrastructure.Api.CreateResponseDescriptor`2.Responder.Execute()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

  on octopus.tf line 15, in resource "octopusdeploy_listening_tentacle_deployment_target" "target":
  15: resource "octopusdeploy_listening_tentacle_deployment_target" "target" {


Releasing state lock. This may take a few moments...
```

Code same as before expectthat im passing `environments = ["xx"]`

**Comment by jbristowe** [comment] 2021-04-22 03:22
Upon reviewing the stack trace, I noticed the rule, `TenantsFiltersAndTenantedDeploymentParticipationAgreeRule` is throwing the exception. This rule -- which is enforced by the Octopus API -- states, "TenantedDeploymentParticipation and tenant filters should not be in conflict". These map to the attributes, `tenanted_deployment_participation` and a combination of `tenants` and/or `tenant_tags` on the resource.

**Comment by thcp** [comment] 2021-04-22 10:57
Hi @jbristowe , thank you for the update, from our side we will be holding the rollout of the `octopusdeploy_listening_tentacle_deployment_target` resource.

**Comment by johnsimons** [comment] 2023-02-22 04:33
I was not able to reproduce this issue using v0.10.3.

I will close this issue, if you can still reproduce it in the latest version, please let us know.

**Closed by johnsimons** 2023-02-22 04:33 UTC
Labels: kind/bug
